# -*- coding: utf-8 -*-
{
    'name': 'Studio customizations',
    'version': '18.0.1.0',
    'category': 'Studio',
    'description': u"""
This module has been generated by Odoo Studio.
It contains the apps created with Studio and the customizations of existing apps.
""",
    'author': 'wpc',
    'depends': [
        'fleet',
        'hr_timesheet',
        'point_of_sale',
        'purchase',
        'sale_pdf_quote_builder',
        'web_grid',
        'web_hierarchy',
        'web_studio',
    ],
    'data': [
        'data/ir_model.xml',
        'data/ir_model_fields.xml',
        'data/ir_ui_view.xml',
        'data/ir_actions_act_window.xml',
        'data/ir_actions_report.xml',
        'data/ir_actions_server.xml',
        'data/ir_ui_menu.xml',
        'data/base_automation.xml',
        'data/ir_model_access.xml',
        'data/ir_default.xml',
    ],
    'license': 'OPL-1',
}
